// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/lib/pq"
)

type Article struct {
	GormModel
	Title       string         `json:"title"`
	Source      Source         `json:"source" gorm:"index"`
	PublishedAt time.Time      `json:"publishedAt" gorm:"index"`
	URI         string         `json:"uri"`
	Views       int32          `json:"views" gorm:"index"`
	Description string         `json:"description"`
	Banner      string         `json:"banner"`
	LinkedTo    []*Article     `json:"linkedTo,omitempty" gorm:"many2many:article_links;joinForeignKey:ArticleID;joinReferences:LinkedArticleID;constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`
	Category    pq.StringArray `json:"category,omitempty" gorm:"type:text[]"`
	Language    Language       `json:"language" gorm:"index"`
	Keywords    []*KeyWords    `json:"keywords,omitempty" gorm:"many2many:article_keywords;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;"`
	LinkedFrom  []*Article     `json:"-" gorm:"many2many:article_links;joinForeignKey:LinkedArticleID;joinReferences:ArticleID;constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`
}

type KeyWords struct {
	GormModel
	Keyword    string     `json:"keyword" gorm:"index"`
	LastUpdate time.Time  `json:"lastUpdate"`
	Articles   []*Article `json:"articles,omitempty" gorm:"many2many:article_keywords;constraint:OnUpdate:CASCADE,OnDelete:SET NULL;"`
}

type Query struct {
}

type ResponseKeyWords struct {
	ID         string     `json:"id"`
	Keyword    string     `json:"keyword"`
	LastUpdate time.Time  `json:"lastUpdate"`
	Articles   []*Article `json:"articles"`
}

type Source string

const (
	SourceTagesschau   Source = "Tagesschau"
	SourceSueddeutsche Source = "Sueddeutsche"
	SourceDieZeit      Source = "DieZeit"
	SourceFaz          Source = "FAZ"
	SourceWelt         Source = "Welt"
	SourceTaz          Source = "TAZ"
	SourceHandelsblatt Source = "Handelsblatt"
)

var AllSource = []Source{
	SourceTagesschau,
	SourceSueddeutsche,
	SourceDieZeit,
	SourceFaz,
	SourceWelt,
	SourceTaz,
	SourceHandelsblatt,
}

func (e Source) IsValid() bool {
	switch e {
	case SourceTagesschau, SourceSueddeutsche, SourceDieZeit, SourceFaz, SourceWelt, SourceTaz, SourceHandelsblatt:
		return true
	}
	return false
}

func (e Source) String() string {
	return string(e)
}

func (e *Source) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Source(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Source", str)
	}
	return nil
}

func (e Source) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Source) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Source) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleAdmin   UserRole = "ADMIN"
	UserRoleUser    UserRole = "USER"
	UserRolePremium UserRole = "PREMIUM"
)

var AllUserRole = []UserRole{
	UserRoleAdmin,
	UserRoleUser,
	UserRolePremium,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleAdmin, UserRoleUser, UserRolePremium:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
